version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./scripts/docker-entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - AUTO_MIGRATE=true
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # マイグレーション専用サービス
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head && python -m app.db.init_db"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    profiles: ["tools"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: